using NLP;
using System.Text;
using System.Text.RegularExpressions;

namespace LTP
{
    public class FunctionExtractor
    {
        public static readonly string FUNCTION = "虚词";
        public static readonly string ADVERB = "副词";
        public static readonly string PRONOUN = "代词";
        public static readonly string PADDING = "衬字词";
        public static readonly string AUXILIARY = "助词";
        public static readonly string LOCATIVE = "方位词";
        public static readonly string PREPOSITION = "介词";
        public static readonly string CONJUNCTION = "连词";

        private static readonly string[][] FUNCTIONS = new string[][]
        {
            new string[] {"照着", PREPOSITION},
            new string[] {"者", AUXILIARY},
            new string[] {"这", PRONOUN},
            new string[] {"这儿", PRONOUN},
            new string[] {"这个", PRONOUN},
            new string[] {"这会儿", PRONOUN},
            new string[] {"这里", PRONOUN},
            new string[] {"这么", PRONOUN},
            new string[] {"这么点儿", PRONOUN},
            new string[] {"这么些", PRONOUN},
            new string[] {"这么样", PRONOUN},
            new string[] {"这么着", PRONOUN},
            new string[] {"这些", PRONOUN},
            new string[] {"这些个", PRONOUN},
            new string[] {"这样", PRONOUN},
            new string[] {"这阵儿", PRONOUN},
            new string[] {"这阵子", PRONOUN},
            new string[] {"真", ADVERB},
            new string[] {"真的", ADVERB},
            new string[] {"真个", ADVERB},
            new string[] {"真是", ADVERB},
            new string[] {"真正", ADVERB},
            new string[] {"正", ADVERB},
            new string[] {"正好", ADVERB},
            new string[] {"正巧", ADVERB},
            new string[] {"正在", ADVERB},
            new string[] {"之", AUXILIARY},
            new string[] {"之", PRONOUN},
            new string[] {"之后", LOCATIVE},
            new string[] {"之间", LOCATIVE},
            new string[] {"之内", LOCATIVE},
            new string[] {"之前", LOCATIVE},
            new string[] {"之上", LOCATIVE},
            new string[] {"之外", LOCATIVE},
            new string[] {"之下", LOCATIVE},
            new string[] {"之中", LOCATIVE},
            new string[] {"直", ADVERB},
            new string[] {"只", ADVERB},
            new string[] {"只顾", ADVERB},
            new string[] {"只管", ADVERB},
            new string[] {"只好", ADVERB},
            new string[] {"只是", CONJUNCTION},
            new string[] {"只是", ADVERB},
            new string[] {"只消", ADVERB},
            new string[] {"只要", CONJUNCTION},
            new string[] {"只有", CONJUNCTION},
            new string[] {"只有", ADVERB},
            new string[] {"至", ADVERB},
            new string[] {"至", CONJUNCTION},
            new string[] {"至多", ADVERB},
            new string[] {"至今", ADVERB},
            new string[] {"至少", ADVERB},
            new string[] {"至为", ADVERB},
            new string[] {"至于", CONJUNCTION},
            new string[] {"致", CONJUNCTION},
            new string[] {"致使", CONJUNCTION},
            new string[] {"中", LOCATIVE},
            new string[] {"终", ADVERB},
            new string[] {"终归", ADVERB},
            new string[] {"终究", ADVERB},
            new string[] {"终久", ADVERB},
            new string[] {"终日", ADVERB},
            new string[] {"终于", ADVERB},
            new string[] {"重新", ADVERB},
            new string[] {"重行", ADVERB},
            new string[] {"骤然", ADVERB},
            new string[] {"逐步", ADVERB},
            new string[] {"逐个", ADVERB},
            new string[] {"逐渐", ADVERB},
            new string[] {"逐年", ADVERB},
            new string[] {"逐日", ADVERB},
            new string[] {"逐一", ADVERB},
            new string[] {"逐月", ADVERB},
            new string[] {"专", ADVERB},
            new string[] {"专门", ADVERB},
            new string[] {"准", ADVERB},
            new string[] {"准保", ADVERB},
            new string[] {"着", AUXILIARY},
            new string[] {"着呐", AUXILIARY},
            new string[] {"着呢", AUXILIARY},
            new string[] {"着实", ADVERB},
            new string[] {"自", PRONOUN},
            new string[] {"自", PREPOSITION},
            new string[] {"自从", PREPOSITION},
            new string[] {"自个", PRONOUN},
            new string[] {"自己", PRONOUN},
            new string[] {"自来", ADVERB},
            new string[] {"自然", CONJUNCTION},
            new string[] {"自然", ADVERB},
            new string[] {"总", ADVERB},
            new string[] {"总共", ADVERB},
            new string[] {"总归", ADVERB},
            new string[] {"总是", ADVERB},
            new string[] {"总算", ADVERB},
            new string[] {"总之", CONJUNCTION},
            new string[] {"纵", CONJUNCTION},
            new string[] {"纵令", CONJUNCTION},
            new string[] {"纵然", CONJUNCTION},
            new string[] {"纵使", CONJUNCTION},
            new string[] {"足", ADVERB},
            new string[] {"足见", CONJUNCTION},
            new string[] {"足足", ADVERB},
            new string[] {"最", ADVERB},
            new string[] {"最多", ADVERB},
            new string[] {"最好", ADVERB},
            new string[] {"最少", ADVERB},
            new string[] {"最为", ADVERB},
            new string[] {"遵照", PREPOSITION},
            new string[] {"无须", ADVERB},
            new string[] {"无庸", ADVERB},
            new string[] {"无足", ADVERB},
            new string[] {"毋", ADVERB},
            new string[] {"毋宁", CONJUNCTION},
            new string[] {"毋庸", ADVERB},
            new string[] {"兀地", ADVERB},
            new string[] {"勿", ADVERB},
            new string[] {"勿宁", CONJUNCTION},
            new string[] {"务", ADVERB},
            new string[] {"务必", ADVERB},
            new string[] {"务须", ADVERB},
            new string[] {"悉", ADVERB},
            new string[] {"稀", ADVERB},
            new string[] {"下", LOCATIVE},
            new string[] {"先", ADVERB},
            new string[] {"先后", ADVERB},
            new string[] {"显然", ADVERB},
            new string[] {"险些", ADVERB},
            new string[] {"相当", ADVERB},
            new string[] {"相继", ADVERB},
            new string[] {"想必", ADVERB},
            new string[] {"向", PREPOSITION},
            new string[] {"向来", ADVERB},
            new string[] {"些微", ADVERB},
            new string[] {"新近", ADVERB},
            new string[] {"兴许", ADVERB},
            new string[] {"行将", ADVERB},
            new string[] {"幸而", ADVERB},
            new string[] {"幸好", ADVERB},
            new string[] {"幸亏", ADVERB},
            new string[] {"休", ADVERB},
            new string[] {"许", ADVERB},
            new string[] {"旋即", ADVERB},
            new string[] {"迅即", ADVERB},
            new string[] {"呀", AUXILIARY},
            new string[] {"俨然", ADVERB},
            new string[] {"要", CONJUNCTION},
            new string[] {"要", ADVERB},
            new string[] {"要不", CONJUNCTION},
            new string[] {"要不然", CONJUNCTION},
            new string[] {"要不是", CONJUNCTION},
            new string[] {"要就", CONJUNCTION},
            new string[] {"要就是", CONJUNCTION},
            new string[] {"要么", CONJUNCTION},
            new string[] {"要末", CONJUNCTION},
            new string[] {"要是", CONJUNCTION},
            new string[] {"也", AUXILIARY},
            new string[] {"也", ADVERB},
            new string[] {"也罢", AUXILIARY},
            new string[] {"也好", AUXILIARY},
            new string[] {"也许", ADVERB},
            new string[] {"业已", ADVERB},
            new string[] {"一", ADVERB},
            new string[] {"一边", CONJUNCTION},
            new string[] {"一并", ADVERB},
            new string[] {"一旦", ADVERB},
            new string[] {"一道", ADVERB},
            new string[] {"一定", ADVERB},
            new string[] {"一度", ADVERB},
            new string[] {"一发", ADVERB},
            new string[] {"一方面", CONJUNCTION},
            new string[] {"一概", ADVERB},
            new string[] {"一共", ADVERB},
            new string[] {"一经", CONJUNCTION},
            new string[] {"一块儿", ADVERB},
            new string[] {"一来", CONJUNCTION},
            new string[] {"一连", ADVERB},
            new string[] {"一溜烟", ADVERB},
            new string[] {"一律", ADVERB},
            new string[] {"一面", CONJUNCTION},
            new string[] {"一齐", ADVERB},
            new string[] {"一起", ADVERB},
            new string[] {"一气", ADVERB},
            new string[] {"一切", PRONOUN},
            new string[] {"一时", ADVERB},
            new string[] {"一同", ADVERB},
            new string[] {"一头", CONJUNCTION},
            new string[] {"一味", ADVERB},
            new string[] {"一向", ADVERB},
            new string[] {"一一", ADVERB},
            new string[] {"一再", ADVERB},
            new string[] {"一则", CONJUNCTION},
            new string[] {"一眨眼", ADVERB},
            new string[] {"一者", CONJUNCTION},
            new string[] {"一直", ADVERB},
            new string[] {"一准", ADVERB},
            new string[] {"一总", ADVERB},
            new string[] {"依", PREPOSITION},
            new string[] {"依次", ADVERB},
            new string[] {"依照", PREPOSITION},
            new string[] {"已", ADVERB},
            new string[] {"已经", ADVERB},
            new string[] {"以", PREPOSITION},
            new string[] {"以", CONJUNCTION},
            new string[] {"以便", CONJUNCTION},
            new string[] {"以便于", CONJUNCTION},
            new string[] {"以后", LOCATIVE},
            new string[] {"以及", CONJUNCTION},
            new string[] {"以免", CONJUNCTION},
            new string[] {"以内", LOCATIVE},
            new string[] {"以前", LOCATIVE},
            new string[] {"以上", LOCATIVE},
            new string[] {"以外", LOCATIVE},
            new string[] {"以下", LOCATIVE},
            new string[] {"以至", CONJUNCTION},
            new string[] {"以致", CONJUNCTION},
            new string[] {"异常", ADVERB},
            new string[] {"抑或", CONJUNCTION},
            new string[] {"益", ADVERB},
            new string[] {"益发", ADVERB},
            new string[] {"因", CONJUNCTION},
            new string[] {"因", PREPOSITION},
            new string[] {"因此", CONJUNCTION},
            new string[] {"因而", CONJUNCTION},
            new string[] {"因为", PREPOSITION},
            new string[] {"因为", CONJUNCTION},
            new string[] {"硬", ADVERB},
            new string[] {"硬是", ADVERB},
            new string[] {"永", ADVERB},
            new string[] {"永远", ADVERB},
            new string[] {"尤", ADVERB},
            new string[] {"尤其", ADVERB},
            new string[] {"尤其是", CONJUNCTION},
            new string[] {"尤为", ADVERB},
            new string[] {"由", PREPOSITION},
            new string[] {"由于", CONJUNCTION},
            new string[] {"由于", PREPOSITION},
            new string[] {"犹", ADVERB},
            new string[] {"犹", CONJUNCTION},
            new string[] {"有的", PRONOUN},
            new string[] {"有点儿", ADVERB},
            new string[] {"有时", ADVERB},
            new string[] {"有些", ADVERB},
            new string[] {"有些", PRONOUN},
            new string[] {"又", ADVERB},
            new string[] {"于", PREPOSITION},
            new string[] {"于是", CONJUNCTION},
            new string[] {"与", CONJUNCTION},
            new string[] {"与", PREPOSITION},
            new string[] {"与其", CONJUNCTION},
            new string[] {"预先", ADVERB},
            new string[] {"愈", ADVERB},
            new string[] {"愈加", ADVERB},
            new string[] {"愈为", ADVERB},
            new string[] {"愈益", ADVERB},
            new string[] {"原", ADVERB},
            new string[] {"原来", ADVERB},
            new string[] {"远", ADVERB},
            new string[] {"约", ADVERB},
            new string[] {"约摸", ADVERB},
            new string[] {"约莫", ADVERB},
            new string[] {"越", ADVERB},
            new string[] {"越发", ADVERB},
            new string[] {"越加", ADVERB},
            new string[] {"再", ADVERB},
            new string[] {"再不", CONJUNCTION},
            new string[] {"再不然", CONJUNCTION},
            new string[] {"再次", ADVERB},
            new string[] {"再度", ADVERB},
            new string[] {"再三", ADVERB},
            new string[] {"再说", CONJUNCTION},
            new string[] {"再则", CONJUNCTION},
            new string[] {"再者", CONJUNCTION},
            new string[] {"在", ADVERB},
            new string[] {"在", PREPOSITION},
            new string[] {"在下", PRONOUN},
            new string[] {"切", ADVERB},
            new string[] {"且", CONJUNCTION},
            new string[] {"且", ADVERB},
            new string[] {"顷刻", ADVERB},
            new string[] {"穷", ADVERB},
            new string[] {"全", ADVERB},
            new string[] {"全都", ADVERB},
            new string[] {"全盘", ADVERB},
            new string[] {"全然", ADVERB},
            new string[] {"权", ADVERB},
            new string[] {"权且", ADVERB},
            new string[] {"却", ADVERB},
            new string[] {"确", ADVERB},
            new string[] {"确乎", ADVERB},
            new string[] {"确然", ADVERB},
            new string[] {"确实", ADVERB},
            new string[] {"然", CONJUNCTION},
            new string[] {"然而", CONJUNCTION},
            new string[] {"然后", CONJUNCTION},
            new string[] {"让", PREPOSITION},
            new string[] {"人家", PRONOUN},
            new string[] {"任", CONJUNCTION},
            new string[] {"任", PREPOSITION},
            new string[] {"任何", PRONOUN},
            new string[] {"任凭", CONJUNCTION},
            new string[] {"任凭", PREPOSITION},
            new string[] {"仍旧", ADVERB},
            new string[] {"仍然", ADVERB},
            new string[] {"日见", ADVERB},
            new string[] {"日渐", ADVERB},
            new string[] {"日趋", ADVERB},
            new string[] {"日日", ADVERB},
            new string[] {"日益", ADVERB},
            new string[] {"日臻", ADVERB},
            new string[] {"如", CONJUNCTION},
            new string[] {"如此", PRONOUN},
            new string[] {"如果", CONJUNCTION},
            new string[] {"如何", PRONOUN},
            new string[] {"如若", CONJUNCTION},
            new string[] {"若", CONJUNCTION},
            new string[] {"若是", CONJUNCTION},
            new string[] {"啥", PRONOUN},
            new string[] {"煞", ADVERB},
            new string[] {"霎时", ADVERB},
            new string[] {"上", LOCATIVE},
            new string[] {"尚", ADVERB},
            new string[] {"尚", CONJUNCTION},
            new string[] {"尚且", CONJUNCTION},
            new string[] {"稍", ADVERB},
            new string[] {"稍顷", ADVERB},
            new string[] {"稍稍", ADVERB},
            new string[] {"稍微", ADVERB},
            new string[] {"稍为", ADVERB},
            new string[] {"稍许", ADVERB},
            new string[] {"设", CONJUNCTION},
            new string[] {"设若", CONJUNCTION},
            new string[] {"设使", CONJUNCTION},
            new string[] {"深", ADVERB},
            new string[] {"深为", ADVERB},
            new string[] {"甚", ADVERB},
            new string[] {"甚而", CONJUNCTION},
            new string[] {"甚而至于", CONJUNCTION},
            new string[] {"甚为", ADVERB},
            new string[] {"甚至", CONJUNCTION},
            new string[] {"甚至于", CONJUNCTION},
            new string[] {"生", ADVERB},
            new string[] {"省得", CONJUNCTION},
            new string[] {"十分", ADVERB},
            new string[] {"什么", PRONOUN},
            new string[] {"时", ADVERB},
            new string[] {"时常", ADVERB},
            new string[] {"时而", ADVERB},
            new string[] {"时刻", ADVERB},
            new string[] {"时时", ADVERB},
            new string[] {"实", ADVERB},
            new string[] {"实在", ADVERB},
            new string[] {"始终", ADVERB},
            new string[] {"势必", ADVERB},
            new string[] {"咱", PRONOUN},
            new string[] {"咱们", PRONOUN},
            new string[] {"暂", ADVERB},
            new string[] {"暂且", ADVERB},
            new string[] {"早", ADVERB},
            new string[] {"早就", ADVERB},
            new string[] {"早晚", ADVERB},
            new string[] {"早已", ADVERB},
            new string[] {"早早", ADVERB},
            new string[] {"则", ADVERB},
            new string[] {"则已", AUXILIARY},
            new string[] {"贼", ADVERB},
            new string[] {"怎", PRONOUN},
            new string[] {"怎么", PRONOUN},
            new string[] {"怎么样", PRONOUN},
            new string[] {"怎么着", PRONOUN},
            new string[] {"怎奈", CONJUNCTION},
            new string[] {"怎样", PRONOUN},
            new string[] {"曾", ADVERB},
            new string[] {"曾经", ADVERB},
            new string[] {"乍", ADVERB},
            new string[] {"照", PREPOSITION},
            new string[] {"是", ADVERB},
            new string[] {"是", CONJUNCTION},
            new string[] {"首先", ADVERB},
            new string[] {"倏然", ADVERB},
            new string[] {"殊", ADVERB},
            new string[] {"谁", PRONOUN},
            new string[] {"谁知道", CONJUNCTION},
            new string[] {"顺", PREPOSITION},
            new string[] {"丝毫", ADVERB},
            new string[] {"死", ADVERB},
            new string[] {"死死", ADVERB},
            new string[] {"似", ADVERB},
            new string[] {"似乎", ADVERB},
            new string[] {"素常", ADVERB},
            new string[] {"素来", ADVERB},
            new string[] {"速速", ADVERB},
            new string[] {"算了", AUXILIARY},
            new string[] {"算是", ADVERB},
            new string[] {"虽", CONJUNCTION},
            new string[] {"虽然", CONJUNCTION},
            new string[] {"虽说", CONJUNCTION},
            new string[] {"虽说是", CONJUNCTION},
            new string[] {"虽则", CONJUNCTION},
            new string[] {"随", CONJUNCTION},
            new string[] {"随便", CONJUNCTION},
            new string[] {"随后", ADVERB},
            new string[] {"随即", ADVERB},
            new string[] {"随时", ADVERB},
            new string[] {"所", AUXILIARY},
            new string[] {"所以", CONJUNCTION},
            new string[] {"索性", ADVERB},
            new string[] {"他", PRONOUN},
            new string[] {"他们", PRONOUN},
            new string[] {"它", PRONOUN},
            new string[] {"它们", PRONOUN},
            new string[] {"太", ADVERB},
            new string[] {"倘或", CONJUNCTION},
            new string[] {"倘若", CONJUNCTION},
            new string[] {"倘使", CONJUNCTION},
            new string[] {"忒", ADVERB},
            new string[] {"特", ADVERB},
            new string[] {"特别", ADVERB},
            new string[] {"特别是", CONJUNCTION},
            new string[] {"替", PREPOSITION},
            new string[] {"挺", ADVERB},
            new string[] {"通", ADVERB},
            new string[] {"通常", ADVERB},
            new string[] {"通共", ADVERB},
            new string[] {"通过", PREPOSITION},
            new string[] {"通盘", ADVERB},
            new string[] {"通通", ADVERB},
            new string[] {"同", ADVERB},
            new string[] {"同", PREPOSITION},
            new string[] {"同", CONJUNCTION},
            new string[] {"统", ADVERB},
            new string[] {"统共", ADVERB},
            new string[] {"统统", ADVERB},
            new string[] {"透", ADVERB},
            new string[] {"透顶", ADVERB},
            new string[] {"突", ADVERB},
            new string[] {"徒", ADVERB},
            new string[] {"徒然", ADVERB},
            new string[] {"哇", AUXILIARY},
            new string[] {"外", LOCATIVE},
            new string[] {"万", ADVERB},
            new string[] {"万般", ADVERB},
            new string[] {"万分", ADVERB},
            new string[] {"万万", ADVERB},
            new string[] {"万一", CONJUNCTION},
            new string[] {"往", PREPOSITION},
            new string[] {"往往", ADVERB},
            new string[] {"微微", ADVERB},
            new string[] {"为", PREPOSITION},
            new string[] {"为的是", CONJUNCTION},
            new string[] {"为了", CONJUNCTION},
            new string[] {"唯", ADVERB},
            new string[] {"唯独", CONJUNCTION},
            new string[] {"唯独", ADVERB},
            new string[] {"唯其", CONJUNCTION},
            new string[] {"唯有", CONJUNCTION},
            new string[] {"唯有", ADVERB},
            new string[] {"惟", ADVERB},
            new string[] {"惟独", CONJUNCTION},
            new string[] {"惟独", ADVERB},
            new string[] {"惟其", CONJUNCTION},
            new string[] {"惟有", CONJUNCTION},
            new string[] {"惟有", ADVERB},
            new string[] {"委", ADVERB},
            new string[] {"委实", ADVERB},
            new string[] {"未", ADVERB},
            new string[] {"未必", ADVERB},
            new string[] {"未便", ADVERB},
            new string[] {"未尝", ADVERB},
            new string[] {"未免", ADVERB},
            new string[] {"未始", ADVERB},
            new string[] {"未曾", ADVERB},
            new string[] {"我", PRONOUN},
            new string[] {"我们", PRONOUN},
            new string[] {"无比", ADVERB},
            new string[] {"无不", ADVERB},
            new string[] {"就令", CONJUNCTION},
            new string[] {"就使", CONJUNCTION},
            new string[] {"就是", AUXILIARY},
            new string[] {"就是", CONJUNCTION},
            new string[] {"就是", ADVERB},
            new string[] {"就是了", AUXILIARY},
            new string[] {"就算", CONJUNCTION},
            new string[] {"就要", ADVERB},
            new string[] {"居然", ADVERB},
            new string[] {"俱", ADVERB},
            new string[] {"据", PREPOSITION},
            new string[] {"距", PREPOSITION},
            new string[] {"距离", PREPOSITION},
            new string[] {"遽然", ADVERB},
            new string[] {"决", ADVERB},
            new string[] {"决计", ADVERB},
            new string[] {"绝", ADVERB},
            new string[] {"绝顶", ADVERB},
            new string[] {"绝对", ADVERB},
            new string[] {"看", AUXILIARY},
            new string[] {"看样子", CONJUNCTION},
            new string[] {"可", CONJUNCTION},
            new string[] {"可", ADVERB},
            new string[] {"可见", CONJUNCTION},
            new string[] {"可能", ADVERB},
            new string[] {"可是", CONJUNCTION},
            new string[] {"恐怕", ADVERB},
            new string[] {"酷", ADVERB},
            new string[] {"快", ADVERB},
            new string[] {"快要", ADVERB},
            new string[] {"况", CONJUNCTION},
            new string[] {"况且", CONJUNCTION},
            new string[] {"亏", ADVERB},
            new string[] {"啦", AUXILIARY},
            new string[] {"来", "衬字词"},
            new string[] {"来", AUXILIARY},
            new string[] {"来的", AUXILIARY},
            new string[] {"来着", AUXILIARY},
            new string[] {"老", ADVERB},
            new string[] {"老是", ADVERB},
            new string[] {"叻", AUXILIARY},
            new string[] {"嘞", AUXILIARY},
            new string[] {"冷不丁", ADVERB},
            new string[] {"冷不防", ADVERB},
            new string[] {"冷孤丁", ADVERB},
            new string[] {"愣", ADVERB},
            new string[] {"离", PREPOSITION},
            new string[] {"里", LOCATIVE},
            new string[] {"哩", AUXILIARY},
            new string[] {"历来", ADVERB},
            new string[] {"立即", ADVERB},
            new string[] {"立刻", ADVERB},
            new string[] {"立时", ADVERB},
            new string[] {"例如", CONJUNCTION},
            new string[] {"连", ADVERB},
            new string[] {"连", PREPOSITION},
            new string[] {"连连", ADVERB},
            new string[] {"连着", ADVERB},
            new string[] {"良", ADVERB},
            new string[] {"聊", ADVERB},
            new string[] {"了", AUXILIARY},
            new string[] {"了", ADVERB},
            new string[] {"咧", AUXILIARY},
            new string[] {"临", PREPOSITION},
            new string[] {"另", PRONOUN},
            new string[] {"另", ADVERB},
            new string[] {"另外", PRONOUN},
            new string[] {"另外", ADVERB},
            new string[] {"另外", CONJUNCTION},
            new string[] {"另一方面", CONJUNCTION},
            new string[] {"咯", AUXILIARY},
            new string[] {"喽", AUXILIARY},
            new string[] {"陆续", ADVERB},
            new string[] {"屡", ADVERB},
            new string[] {"屡次", ADVERB},
            new string[] {"屡屡", ADVERB},
            new string[] {"略", ADVERB},
            new string[] {"略略", ADVERB},
            new string[] {"略微", ADVERB},
            new string[] {"略为", ADVERB},
            new string[] {"论", PREPOSITION},
            new string[] {"啰", AUXILIARY},
            new string[] {"马上", ADVERB},
            new string[] {"吗", AUXILIARY},
            new string[] {"嘛", AUXILIARY},
            new string[] {"蛮", ADVERB},
            new string[] {"满", ADVERB},
            new string[] {"满处", ADVERB},
            new string[] {"无从", ADVERB},
            new string[] {"无端", ADVERB},
            new string[] {"无非", ADVERB},
            new string[] {"无怪", CONJUNCTION},
            new string[] {"无怪乎", CONJUNCTION},
            new string[] {"无怪于", CONJUNCTION},
            new string[] {"无论", CONJUNCTION},
            new string[] {"无奈", CONJUNCTION},
            new string[] {"无宁", CONJUNCTION},
            new string[] {"无日", ADVERB},
            new string[] {"无上", ADVERB},
            new string[] {"无时", ADVERB},
            new string[] {"慢说", CONJUNCTION},
            new string[] {"慢说是", CONJUNCTION},
            new string[] {"么", AUXILIARY},
            new string[] {"么", PADDING},
            new string[] {"没", ADVERB},
            new string[] {"没有", ADVERB},
            new string[] {"每", PRONOUN},
            new string[] {"每每", ADVERB},
            new string[] {"们", AUXILIARY},
            new string[] {"猛", ADVERB},
            new string[] {"猛不防", ADVERB},
            new string[] {"猛地", ADVERB},
            new string[] {"猛然", ADVERB},
            new string[] {"免得", CONJUNCTION},
            new string[] {"明", ADVERB},
            new string[] {"明明", ADVERB},
            new string[] {"莫", ADVERB},
            new string[] {"莫非", ADVERB},
            new string[] {"莫非是", ADVERB},
            new string[] {"莫如", ADVERB},
            new string[] {"莫若", ADVERB},
            new string[] {"莫说", CONJUNCTION},
            new string[] {"莫说是", CONJUNCTION},
            new string[] {"蓦地", ADVERB},
            new string[] {"蓦然", ADVERB},
            new string[] {"某", PRONOUN},
            new string[] {"拿", PREPOSITION},
            new string[] {"哪", AUXILIARY},
            new string[] {"哪儿", PRONOUN},
            new string[] {"哪会儿", PRONOUN},
            new string[] {"哪里", PRONOUN},
            new string[] {"哪怕", CONJUNCTION},
            new string[] {"哪怕是", CONJUNCTION},
            new string[] {"内", LOCATIVE},
            new string[] {"那", PRONOUN},
            new string[] {"那", CONJUNCTION},
            new string[] {"那儿", PRONOUN},
            new string[] {"那个", PRONOUN},
            new string[] {"那会儿", PRONOUN},
            new string[] {"那里", PRONOUN},
            new string[] {"那么", PRONOUN},
            new string[] {"那么", CONJUNCTION},
            new string[] {"那么点儿", PRONOUN},
            new string[] {"那么些", PRONOUN},
            new string[] {"那么样", PRONOUN},
            new string[] {"那么着", PRONOUN},
            new string[] {"那末", CONJUNCTION},
            new string[] {"那些", PRONOUN},
            new string[] {"那些个", PRONOUN},
            new string[] {"那样", PRONOUN},
            new string[] {"那阵儿", PRONOUN},
            new string[] {"那阵子", PRONOUN},
            new string[] {"乃", PRONOUN},
            new string[] {"乃", ADVERB},
            new string[] {"乃至", CONJUNCTION},
            new string[] {"乃至于", CONJUNCTION},
            new string[] {"难道", ADVERB},
            new string[] {"难怪", ADVERB},
            new string[] {"难免", ADVERB},
            new string[] {"呐", AUXILIARY},
            new string[] {"呢", AUXILIARY},
            new string[] {"你", PRONOUN},
            new string[] {"你们", PRONOUN},
            new string[] {"您", PRONOUN},
            new string[] {"宁", ADVERB},
            new string[] {"宁可", ADVERB},
            new string[] {"宁肯", ADVERB},
            new string[] {"宁愿", ADVERB},
            new string[] {"噢", AUXILIARY},
            new string[] {"哦", AUXILIARY},
            new string[] {"偶", ADVERB},
            new string[] {"偶而", ADVERB},
            new string[] {"偶尔", ADVERB},
            new string[] {"偶或", ADVERB},
            new string[] {"怕", ADVERB},
            new string[] {"怕是", ADVERB},
            new string[] {"譬如", CONJUNCTION},
            new string[] {"偏", ADVERB},
            new string[] {"偏偏", ADVERB},
            new string[] {"偏巧", ADVERB},
            new string[] {"频", ADVERB},
            new string[] {"频频", ADVERB},
            new string[] {"凭", PREPOSITION},
            new string[] {"凭", CONJUNCTION},
            new string[] {"凭着", PREPOSITION},
            new string[] {"颇", ADVERB},
            new string[] {"颇为", ADVERB},
            new string[] {"齐", ADVERB},
            new string[] {"其", PRONOUN},
            new string[] {"其实", ADVERB},
            new string[] {"其他", PRONOUN},
            new string[] {"其余", PRONOUN},
            new string[] {"岂", ADVERB},
            new string[] {"岂但", CONJUNCTION},
            new string[] {"起初", ADVERB},
            new string[] {"起码", ADVERB},
            new string[] {"起先", ADVERB},
            new string[] {"恰好", ADVERB},
            new string[] {"恰恰", ADVERB},
            new string[] {"恰巧", ADVERB},
            new string[] {"俄尔", ADVERB},
            new string[] {"而", CONJUNCTION},
            new string[] {"而后", CONJUNCTION},
            new string[] {"而况", CONJUNCTION},
            new string[] {"而且", CONJUNCTION},
            new string[] {"而已", AUXILIARY},
            new string[] {"尔后", CONJUNCTION},
            new string[] {"凡", ADVERB},
            new string[] {"凡是", ADVERB},
            new string[] {"反", ADVERB},
            new string[] {"反倒", ADVERB},
            new string[] {"反而", ADVERB},
            new string[] {"反复", ADVERB},
            new string[] {"反正", ADVERB},
            new string[] {"反之", CONJUNCTION},
            new string[] {"方", ADVERB},
            new string[] {"方才", ADVERB},
            new string[] {"仿佛", ADVERB},
            new string[] {"非", ADVERB},
            new string[] {"非常", ADVERB},
            new string[] {"非但", CONJUNCTION},
            new string[] {"非特", CONJUNCTION},
            new string[] {"分外", ADVERB},
            new string[] {"否", AUXILIARY},
            new string[] {"否则", CONJUNCTION},
            new string[] {"该", PRONOUN},
            new string[] {"该", ADVERB},
            new string[] {"概", ADVERB},
            new string[] {"赶", PREPOSITION},
            new string[] {"赶紧", ADVERB},
            new string[] {"敢情", ADVERB},
            new string[] {"敢是", ADVERB},
            new string[] {"刚", ADVERB},
            new string[] {"刚刚", ADVERB},
            new string[] {"刚好", ADVERB},
            new string[] {"刚巧", ADVERB},
            new string[] {"高低", ADVERB},
            new string[] {"格外", ADVERB},
            new string[] {"各", PRONOUN},
            new string[] {"各自", PRONOUN},
            new string[] {"给", PREPOSITION},
            new string[] {"根本", ADVERB},
            new string[] {"根据", PREPOSITION},
            new string[] {"跟", PREPOSITION},
            new string[] {"跟", CONJUNCTION},
            new string[] {"更", ADVERB},
            new string[] {"更加", ADVERB},
            new string[] {"更其", ADVERB},
            new string[] {"更为", ADVERB},
            new string[] {"共", ADVERB},
            new string[] {"共同", ADVERB},
            new string[] {"共总", ADVERB},
            new string[] {"够", ADVERB},
            new string[] {"姑", ADVERB},
            new string[] {"姑且", ADVERB},
            new string[] {"固", ADVERB},
            new string[] {"固然", CONJUNCTION},
            new string[] {"故", CONJUNCTION},
            new string[] {"怪", ADVERB},
            new string[] {"怪不得", CONJUNCTION},
            new string[] {"关于", PREPOSITION},
            new string[] {"管", PREPOSITION},
            new string[] {"管", CONJUNCTION},
            new string[] {"光", ADVERB},
            new string[] {"光景", CONJUNCTION},
            new string[] {"归", PREPOSITION},
            new string[] {"果", ADVERB},
            new string[] {"果然", ADVERB},
            new string[] {"果然", CONJUNCTION},
            new string[] {"果真", CONJUNCTION},
            new string[] {"果真", ADVERB},
            new string[] {"过", ADVERB},
            new string[] {"过", AUXILIARY},
            new string[] {"过分", ADVERB},
            new string[] {"过于", ADVERB},
            new string[] {"毫", ADVERB},
            new string[] {"好", ADVERB},
            new string[] {"好", CONJUNCTION},
            new string[] {"好不", ADVERB},
            new string[] {"好歹", ADVERB},
            new string[] {"好了", AUXILIARY},
            new string[] {"好生", ADVERB},
            new string[] {"好像", ADVERB},
            new string[] {"好在", ADVERB},
            new string[] {"呵", AUXILIARY},
            new string[] {"何", PRONOUN},
            new string[] {"何必", ADVERB},
            new string[] {"何不", ADVERB},
            new string[] {"何尝", ADVERB},
            new string[] {"何等", ADVERB},
            new string[] {"何苦", ADVERB},
            new string[] {"何况", CONJUNCTION},
            new string[] {"何其", ADVERB},
            new string[] {"何曾", ADVERB},
            new string[] {"和", CONJUNCTION},
            new string[] {"和", PREPOSITION},
            new string[] {"很", CONJUNCTION},
            new string[] {"很", ADVERB},
            new string[] {"千万", ADVERB},
            new string[] {"前", LOCATIVE},
            new string[] {"啊", AUXILIARY},
            new string[] {"按", PREPOSITION},
            new string[] {"按照", PREPOSITION},
            new string[] {"叭", AUXILIARY},
            new string[] {"吧", AUXILIARY},
            new string[] {"把", AUXILIARY},
            new string[] {"把", PREPOSITION},
            new string[] {"横竖", ADVERB},
            new string[] {"后", LOCATIVE},
            new string[] {"忽", ADVERB},
            new string[] {"忽地", ADVERB},
            new string[] {"忽而", ADVERB},
            new string[] {"忽然", ADVERB},
            new string[] {"还", ADVERB},
            new string[] {"还是", ADVERB},
            new string[] {"还是", CONJUNCTION},
            new string[] {"恍", ADVERB},
            new string[] {"活", ADVERB},
            new string[] {"或", ADVERB},
            new string[] {"或", CONJUNCTION},
            new string[] {"或是", CONJUNCTION},
            new string[] {"或许", ADVERB},
            new string[] {"或则", CONJUNCTION},
            new string[] {"或者", CONJUNCTION},
            new string[] {"霍地", ADVERB},
            new string[] {"霍然", ADVERB},
            new string[] {"基本", ADVERB},
            new string[] {"基本上", ADVERB},
            new string[] {"基于", PREPOSITION},
            new string[] {"及", CONJUNCTION},
            new string[] {"及至", PREPOSITION},
            new string[] {"即", ADVERB},
            new string[] {"即", CONJUNCTION},
            new string[] {"即便", CONJUNCTION},
            new string[] {"即将", ADVERB},
            new string[] {"即刻", ADVERB},
            new string[] {"即使", CONJUNCTION},
            new string[] {"极", ADVERB},
            new string[] {"极度", ADVERB},
            new string[] {"极端", ADVERB},
            new string[] {"极其", ADVERB},
            new string[] {"极为", ADVERB},
            new string[] {"籍", PREPOSITION},
            new string[] {"几", ADVERB},
            new string[] {"几乎", ADVERB},
            new string[] {"己", PRONOUN},
            new string[] {"既", CONJUNCTION},
            new string[] {"既而", ADVERB},
            new string[] {"既然", CONJUNCTION},
            new string[] {"既是", CONJUNCTION},
            new string[] {"继而", ADVERB},
            new string[] {"暨", CONJUNCTION},
            new string[] {"加上", CONJUNCTION},
            new string[] {"加以", CONJUNCTION},
            new string[] {"加之", CONJUNCTION},
            new string[] {"假如", CONJUNCTION},
            new string[] {"假若", CONJUNCTION},
            new string[] {"假使", CONJUNCTION},
            new string[] {"间", LOCATIVE},
            new string[] {"间或", ADVERB},
            new string[] {"简直", ADVERB},
            new string[] {"渐", ADVERB},
            new string[] {"渐次", ADVERB},
            new string[] {"渐渐", ADVERB},
            new string[] {"鉴于", CONJUNCTION},
            new string[] {"鉴于", PREPOSITION},
            new string[] {"将", ADVERB},
            new string[] {"将次", ADVERB},
            new string[] {"将要", ADVERB},
            new string[] {"叫", PREPOSITION},
            new string[] {"较", ADVERB},
            new string[] {"较", PREPOSITION},
            new string[] {"较比", ADVERB},
            new string[] {"较为", ADVERB},
            new string[] {"教", PREPOSITION},
            new string[] {"皆", ADVERB},
            new string[] {"接连", ADVERB},
            new string[] {"结果", CONJUNCTION},
            new string[] {"她", PRONOUN},
            new string[] {"她们", PRONOUN},
            new string[] {"借", PREPOSITION},
            new string[] {"仅", ADVERB},
            new string[] {"仅仅", ADVERB},
            new string[] {"尽", ADVERB},
            new string[] {"尽", PREPOSITION},
            new string[] {"尽管", ADVERB},
            new string[] {"尽管", CONJUNCTION},
            new string[] {"尽量", ADVERB},
            new string[] {"进而", CONJUNCTION},
            new string[] {"经", PREPOSITION},
            new string[] {"经常", ADVERB},
            new string[] {"经过", PREPOSITION},
            new string[] {"净", ADVERB},
            new string[] {"竟", ADVERB},
            new string[] {"竟然", ADVERB},
            new string[] {"竟自", ADVERB},
            new string[] {"究竟", ADVERB},
            new string[] {"久久", ADVERB},
            new string[] {"就", ADVERB},
            new string[] {"就", PREPOSITION},
            new string[] {"罢", AUXILIARY},
            new string[] {"罢了", AUXILIARY},
            new string[] {"呗", AUXILIARY},
            new string[] {"备", ADVERB},
            new string[] {"备加", ADVERB},
            new string[] {"倍", ADVERB},
            new string[] {"倍儿", ADVERB},
            new string[] {"倍加", ADVERB},
            new string[] {"被", PREPOSITION},
            new string[] {"本", ADVERB},
            new string[] {"本", PREPOSITION},
            new string[] {"本来", ADVERB},
            new string[] {"本人", PRONOUN},
            new string[] {"本着", PREPOSITION},
            new string[] {"甭", ADVERB},
            new string[] {"甭说", CONJUNCTION},
            new string[] {"甭说是", CONJUNCTION},
            new string[] {"比", PREPOSITION},
            new string[] {"比方", CONJUNCTION},
            new string[] {"比较", ADVERB},
            new string[] {"比如", CONJUNCTION},
            new string[] {"彼", ADVERB},
            new string[] {"彼此", PRONOUN},
            new string[] {"必", ADVERB},
            new string[] {"必定", ADVERB},
            new string[] {"必然", ADVERB},
            new string[] {"必须", ADVERB},
            new string[] {"边", ADVERB},
            new string[] {"便", CONJUNCTION},
            new string[] {"便", ADVERB},
            new string[] {"便是", CONJUNCTION},
            new string[] {"别", ADVERB},
            new string[] {"别管", CONJUNCTION},
            new string[] {"别看", CONJUNCTION},
            new string[] {"别人", PRONOUN},
            new string[] {"别说", CONJUNCTION},
            new string[] {"别说是", CONJUNCTION},
            new string[] {"并", ADVERB},
            new string[] {"并", CONJUNCTION},
            new string[] {"并且", CONJUNCTION},
            new string[] {"不", ADVERB},
            new string[] {"不必", ADVERB},
            new string[] {"不便", ADVERB},
            new string[] {"不成", AUXILIARY},
            new string[] {"不大", ADVERB},
            new string[] {"不单", CONJUNCTION},
            new string[] {"不单是", CONJUNCTION},
            new string[] {"不但", CONJUNCTION},
            new string[] {"不独", CONJUNCTION},
            new string[] {"不断", ADVERB},
            new string[] {"不妨", ADVERB},
            new string[] {"不管", CONJUNCTION},
            new string[] {"不光", CONJUNCTION},
            new string[] {"不过", ADVERB},
            new string[] {"不仅", CONJUNCTION},
            new string[] {"不拘", CONJUNCTION},
            new string[] {"不堪", ADVERB},
            new string[] {"不愧", ADVERB},
            new string[] {"不料", CONJUNCTION},
            new string[] {"不论", CONJUNCTION},
            new string[] {"不免", ADVERB},
            new string[] {"不然", CONJUNCTION},
            new string[] {"不如", CONJUNCTION},
            new string[] {"不胜", ADVERB},
            new string[] {"不时", ADVERB},
            new string[] {"不说", CONJUNCTION},
            new string[] {"不特", CONJUNCTION},
            new string[] {"不惟", CONJUNCTION},
            new string[] {"不问", CONJUNCTION},
            new string[] {"不消", ADVERB},
            new string[] {"不屑", ADVERB},
            new string[] {"不要说", CONJUNCTION},
            new string[] {"不意", CONJUNCTION},
            new string[] {"不用", ADVERB},
            new string[] {"不由", ADVERB},
            new string[] {"不曾", ADVERB},
            new string[] {"不止", CONJUNCTION},
            new string[] {"不止", ADVERB},
            new string[] {"不只", CONJUNCTION},
            new string[] {"不至于", ADVERB},
            new string[] {"不致", ADVERB},
            new string[] {"不足", ADVERB},
            new string[] {"才", ADVERB},
            new string[] {"差不多", ADVERB},
            new string[] {"差点儿", ADVERB},
            new string[] {"差一点儿", ADVERB},
            new string[] {"常", ADVERB},
            new string[] {"常常", ADVERB},
            new string[] {"朝", PREPOSITION},
            new string[] {"朝着", PREPOSITION},
            new string[] {"趁", PREPOSITION},
            new string[] {"诚", ADVERB},
            new string[] {"诚然", CONJUNCTION},
            new string[] {"乘", PREPOSITION},
            new string[] {"迟早", ADVERB},
            new string[] {"冲", PREPOSITION},
            new string[] {"初", ADVERB},
            new string[] {"除", PREPOSITION},
            new string[] {"除非", CONJUNCTION},
            new string[] {"除了", PREPOSITION},
            new string[] {"处处", ADVERB},
            new string[] {"纯", ADVERB},
            new string[] {"纯粹", ADVERB},
            new string[] {"此", PRONOUN},
            new string[] {"此外", CONJUNCTION},
            new string[] {"次第", ADVERB},
            new string[] {"从", ADVERB},
            new string[] {"从", PREPOSITION},
            new string[] {"从此", ADVERB},
            new string[] {"从而", CONJUNCTION},
            new string[] {"从来", ADVERB},
            new string[] {"从新", ADVERB},
            new string[] {"匆匆", ADVERB},
            new string[] {"猝然", ADVERB},
            new string[] {"打", PREPOSITION},
            new string[] {"打从", PREPOSITION},
            new string[] {"大", ADVERB},
            new string[] {"大半", ADVERB},
            new string[] {"大大", ADVERB},
            new string[] {"大都", ADVERB},
            new string[] {"大多", ADVERB},
            new string[] {"大凡", ADVERB},
            new string[] {"大概", ADVERB},
            new string[] {"大伙儿", PRONOUN},
            new string[] {"大家", PRONOUN},
            new string[] {"大家伙儿", PRONOUN},
            new string[] {"大体", ADVERB},
            new string[] {"大体上", ADVERB},
            new string[] {"大为", ADVERB},
            new string[] {"大约", ADVERB},
            new string[] {"大致", ADVERB},
            new string[] {"大致上", ADVERB},
            new string[] {"单", ADVERB},
            new string[] {"单单", ADVERB},
            new string[] {"但", CONJUNCTION},
            new string[] {"但凡", CONJUNCTION},
            new string[] {"但是", CONJUNCTION},
            new string[] {"当场", ADVERB},
            new string[] {"当即", ADVERB},
            new string[] {"当面", ADVERB},
            new string[] {"当然", ADVERB},
            new string[] {"当下", ADVERB},
            new string[] {"当真", ADVERB},
            new string[] {"倒", ADVERB},
            new string[] {"倒是", ADVERB},
            new string[] {"到处", ADVERB},
            new string[] {"到底", ADVERB},
            new string[] {"得", AUXILIARY},
            new string[] {"得了", AUXILIARY},
            new string[] {"的", AUXILIARY},
            new string[] {"的话", AUXILIARY},
            new string[] {"的确", ADVERB},
            new string[] {"登时", ADVERB},
            new string[] {"地", AUXILIARY},
            new string[] {"迭", ADVERB},
            new string[] {"顶", ADVERB},
            new string[] {"顶顶", ADVERB},
            new string[] {"顶好", ADVERB},
            new string[] {"定", ADVERB},
            new string[] {"定然", ADVERB},
            new string[] {"定准", ADVERB},
            new string[] {"动辄", ADVERB},
            new string[] {"都", ADVERB},
            new string[] {"陡然", ADVERB},
            new string[] {"独", ADVERB},
            new string[] {"独独", ADVERB},
            new string[] {"独自", ADVERB},
            new string[] {"断", ADVERB},
            new string[] {"断断", ADVERB},
            new string[] {"断乎", ADVERB},
            new string[] {"断然", ADVERB},
            new string[] {"对", PREPOSITION},
            new string[] {"对于", PREPOSITION},
            new string[] {"顿", ADVERB},
            new string[] {"顿时", ADVERB},
            new string[] {"多", PRONOUN},
            new string[] {"多", ADVERB},
            new string[] {"多半", ADVERB},
            new string[] {"多亏", ADVERB},
            new string[] {"多么", ADVERB},
            new string[] {"多少", ADVERB},
            new string[] {"多少", PRONOUN},
            new string[] {"俄而", ADVERB},
        };

#if _USE_CLR
        public static FunctionSegment[] Extract(string content)
#elif _USE_CONSOLE
        public static FunctionSegment[]? Extract(string content)
#endif
        {
            // 检查参数
            if (content == null ||
                content.Length <= 0) return null;

#if _USE_CLR
            // 获得匹配的项目
            FunctionSegment[] output =
#elif _USE_CONSOLE
            // 获得匹配的项目
            FunctionSegment[]? output =
#endif
                FunctionSegment.Extract(content, FUNCTIONS);
            // 检查结果
            if (output == null || output.Length <= 0) return null;

            // 循环处理
            foreach (FunctionSegment fs in output) fs.Remark = FUNCTION;
            // 返回结果
            return output;
        }

#if _USE_CONSOLE
        public static void Main(string[] args)
        {
            int sid = -1;
            // 尝试解析
            if (!int.TryParse(args[1], out sid))
            {
                Console.WriteLine("请输入正确的参数！"); return;
            }

            // 生成随机数
            Random random = new Random();

            do
            {
                // 获得内容
                string? content =
                    ShortContent.GetContent(sid);
                // 检查内容
                if (string.IsNullOrEmpty(content))
                {
                    Console.WriteLine("RawContent.GetContent返回空字符串！");
                }
                else
                {
                    // 打印原始内容
                    Console.WriteLine("----------------------------------------");
                    Console.WriteLine("打印RawContent.GetContent(" + sid + ")内容！");
                    Console.WriteLine("----------------------------------------");
                    Console.WriteLine(content);

                    // 清理内容
                    content =
                        MiscTool.ClearContent(content);
                    // 检查内容
                    if (string.IsNullOrEmpty(content))
                    {
                        Console.WriteLine("MiscTool.ClearContent返回空字符串！");
                    }
                    else
                    {
                        // 打印清洗后的内容
                        Console.WriteLine("----------------------------------------");
                        Console.WriteLine("打印MiscTool.ClearContent(" + sid + ")内容！");
                        Console.WriteLine("----------------------------------------");
                        Console.WriteLine(content);

                        // 提取数量词
                        FunctionSegment[]? fses = Extract(content);
                        // 检查结果
                        if (fses == null || fses.Length <= 0)
                        {
                            Console.WriteLine("----------------------------------------");
                            Console.WriteLine("FunctionExtractor.ExtractFunctions未找到虚词！");
                        }
                        else
                        {
                            // 打印清洗后的内容
                            Console.WriteLine("----------------------------------------");
                            Console.WriteLine("打印FunctionExtractor.ExtractFunctions(" + sid + ")内容！");
                            Console.WriteLine("----------------------------------------");
                            // 打印所有内容
                            foreach (FunctionSegment fs in fses) fs.Print();
                        }
                    }
                }

                // 随机往下
                sid += random.Next(1, 10);
                // 等待键盘
                if (Console.ReadKey().Key == ConsoleKey.Escape) break;

            } while (true);
        }
#endif
    }
}
